### ISSUE TITLE
EgressClient failed to export stream.

### ISSUE THREAD

**Issue by WeiRU087** [livekit/server-sdk-js#100]
I'm trying to use Egress to push stream with rtmp. The fucntion startRoomCompositeEgress result in TypeError in browser.
Thank you in advance.

![image](https://github.com/livekit/server-sdk-js/assets/78401256/83d8b85d-e2fa-461b-95c2-d05d345c11fc)
![image](https://github.com/livekit/server-sdk-js/assets/78401256/9fda7ef8-7c70-4883-be18-8c9178f67f3c)
![image](https://github.com/livekit/server-sdk-js/assets/78401256/8d437ee7-ca85-4115-9f75-2bb7bd144ca1)

**Comment by davidzhao** [comment]
Server SDK is not designed to be ran within a browser environment. You are seeing this error due to crypto polyfill being incompatible with recent versions.
