### ISSUE TITLE
Text Chat via WebRTC Data Channel is unusable

### ISSUE THREAD

**Issue by cpp-pilot** [livekit/server-sdk-js#101]
The chat implementation in your application is not reliable because messages don't get sent if there are no participants. In reality, they should be stored in history so that a new participant can receive the messages. From the backend and webhook side, I don't see a way to control this. Can you provide any guidance?

**Comment by Ocupe** [comment]
Hey @cpp-pilot, there is currently no build in history for chat or data messages in general. This is something you need to handle on the application layer.
There is discussion about adding persistence, but no timeline yet.

**Comment by cpp-pilot** [comment]
How can I receive messages on the server from the channel? What's the purpose of such a WebRTC data channel if it can't be accessed on the backend? Also, please don't close the issue unilaterally in order to assist the person..

**Comment by Ocupe** [comment]
Hey @cpp-pilot,
here a link to the docs around data messages: https://docs.livekit.io/client/data-messages/#data-messages

> ## Data messages
> From both server and clients, LiveKit lets you publish arbitrary data messages to any participants in the room via the `LocalParticipant.publishData` API. Room data is published to the SFU via WebRTC data channels; and LiveKit server would forward that data to one or more participants in the room.
> 
> From the server side, this API is exposed on `RoomService` as `SendData`

For example you can send data via the Node.js client: https://docs.livekit.io/server-sdk-js/classes/RoomServiceClient.html#sendData or the Go client: https://pkg.go.dev/github.com/livekit/server-sdk-go#RoomServiceClient.SendData

If you are looking for a concrete implementation of a chat component, you can find it here: [Component-JS Chat component](https://github.com/livekit/components-js/blob/2648c602f3aaa4a22068e5923eeb66e841db163b/packages/react/src/prefabs/Chat.tsx#L50)

So you could store your chat history in the backend and then send it to new participants after they join a room.

For more support or questions, please feel free to join the [LiveKit Slack community](https://livekit-users.slack.com/join/shared_invite/zt-202wk1vsl-VR1cnH~w3KrpMyf3P~Ktmw#/shared-invite/email).
