### ISSUE TITLE
Join room using the sdk from server

### ISSUE THREAD

**Issue by noushad-pp** [livekit/server-sdk-js#105]
I'm trying to implement a similar idea that of https://blog.livekit.io/meet-kitt/. I was able to set up a local livekit-server and use a nodeJs app to support creating tokens and rooms. I have also a web hook receiver that is called on room event.
What I want to achieve is to make a bot (text to speech service) respond to the room programmatically but I couldn't find anything from the documentation or code.

Something like [KITT ConnectToRoomWithToken](https://github.com/livekit-examples/kitt/blob/main/lkgpt-service/pkg/service/gptparticipant.go#L106) or [go-server-sdk JoinRoom](https://github.com/livekit/server-sdk-go/blob/main/room.go#L158)

How can I achieve the same using javascript sdk??

**Comment by davidzhao** [comment]
Unfortunately this isn't possible from JS server SDK. Node.js does not implement WebRTC APIs. Currently you could build server-side RTC applications with Go, Python, and Rust.
