### ISSUE TITLE
AccessToken.addGrant() should not replace previous grants

### ISSUE THREAD

**Issue by shahriar-shojib** [livekit/server-sdk-js#109]
Consider this following use case:
```ts

const token = new AccessToken();

token.addGrant({
 canPublish: true,
 canSubscribe: true,
 roomJoin: true,
 room: data.meetingID,
 canPublishData: true,
});

if( user.isAdmin ){
 token.addGrant({  roomAdmin: true })
}

```

This code should keep the previous grants and add `roomAdmin` grant to the token, instead, it replaces previous grants and adds only `roomAdmin` grant to the token.

I am not sure if this is intentional, I was not able to join a room with just `roomAdmin` grant.

I can open a PR that fixes this issue.

https://github.com/livekit/server-sdk-js/blob/e9e24658479c72bbcd156d62f046a51c608d8731/src/AccessToken.ts#L83

**Comment by davidzhao** [comment]
@shahriar-shojib I agree.. since it's called `addGrant`, it should not clear out existing values. If you can open a PR, that'd be great!
