### ISSUE TITLE
Import error in nestjs typescript

### ISSUE THREAD

**Issue by takiuddinahmed** [livekit/server-sdk-js#139]
I am integrating livekit-sdk-js in my nestjs project. It is throwing me import error

```
/home/app/dist/modules/live-stream/services/livekit.services.js:14
const livekit_server_sdk_1 = require("livekit-server-sdk");
                             ^
Error [ERR_REQUIRE_ESM]: require() of ES Module/home/app/node_modules/livekit-server-sdk/dist/index.js from /home/app/dist/modules/live-stream/services/livekit.services.js not supported.
Instead change the require of index.js in /home/app/dist/modules/live-stream/services/livekit.services.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/app/dist/modules/live-stream/services/livekit.services.js:14:30)
```

Livekit version from `package-lock.json`:
```
"node_modules/livekit-server-sdk": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/livekit-server-sdk/-/livekit-server-sdk-2.0.2.tgz",
      "integrity": "sha512-txRuM8HDXTpzKGdwUwL6uJI7AuOeB+a+ozJNO/OWJhf/xLnYmJn4Vwpzar5+DkW10878pfFpu/NsWiu6j3120g==",
      "dependencies": {
        "@bufbuild/protobuf": "^1.3.0",
        "camelcase-keys": "^7.0.0",
        "jose": "^5.1.2"
      },
      "engines": {
        "node": ">=18"
      }
    },
```

and `tsconfig.json`:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

**Comment by lukasIO** [comment]
try setting `module: "es2020"` in your tsconfig. But it doesn't sound to me like NestJS has good ESM support, here's a SO thread discussing some workarounds https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs

**Comment by joaoeudes7** [comment]
On version [v2.0.0](https://github.com/livekit/server-sdk-js/releases/tag/v2.0.0) the library changed the module type to ESM and Require node 18 as minimum version, that maybe resolve your problem:

tsconfig.json:
```json
{
...
    "target": "ESNext",                    
    "module": "Node16", 
    "moduleResolution": "Node16",    
...
}
```

package.json:

```json
{
...
  "type": "commonjs",
...
}
```

**Comment by mztnnrt** [comment]
Hi, we also using Nestjs and have problem `ERR_REQUIRE_ESM` error.
Then use 1.2.7 version, it's work correctly. Thanks @lukasIO

**Comment by rahulpaulgopireddy** [comment]
it still doesnt work when i downgraded it to 1.2.7 . Were you able to resolve it ? 
this is my package list 
"dependencies": {
    "@clerk/nextjs": "^4.29.7",
    "@clerk/themes": "^1.7.9",
    "@livekit/components-react": "^1.4.2",
    "@prisma/client": "^5.10.2",
    "@radix-ui/react-avatar": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-tooltip": "^1.0.7",
    "add": "^2.0.6",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "livekit-client": "^1.15.4",
    "livekit-server-sdk": "^1.2.7",
    "lucide-react": "^0.338.0",
    "next": "14.1.0",
    "next-themes": "^0.2.1",
    "query-string": "^9.0.0",
    "react": "^18",
    "react-dom": "^18",
    "shadcn-ui": "^0.8.0",
    "sonner": "^1.4.2",
    "svix": "^1.20.0",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "tooltip": "^1.6.1",
    "usehooks-ts": "^2.15.1",
    "zustand": "^4.5.1"
  },

**Comment by tmaximini** [comment]
I am also seeing the `ERR_REQUIRE_ESM` when trying to use `livekit-server-sdk` from serverless / AWS Lambda (using Node 18.x)

**Comment by firasglai** [comment]
same issue with 
my node js with typescript backend 
i tried changing my tsconfig.json and adding the  "type": "module", and "ts-node": {
         "esm": true
     }
     but the only thing that works for me is downgrading it to 
     "livekit-server-sdk": "^1.2.7",
     this is my package.json 

         "devDependencies": {
        "@types/express": "^4.17.21",
        "@types/node": "^20.9.2",
        "prisma": "^5.6.0",
        "ts-node": "^10.9.1",
        "typescript": "^5.4.3"
    },
    "dependencies": {
        "@prisma/client": "^5.6.0",
        "cors": "^2.8.5",
        "dotenv": "^16.3.1",
        "express": "^4.18.2",
        "express-validator": "^7.0.1",
        "livekit-server-sdk": "^1.2.7",
        "morgan": "^1.10.0",
        "nodemon": "^3.0.1",  
        "zod": "^3.22.4"
    }
}

**Comment by lukasIO** [comment]
as one of the nestjs maintainers points out [here](https://github.com/nestjs/nest/pull/8736#issuecomment-1116852269), they seem reluctant to add ESM support. The suggested workaround is to use dynamic imports, i.e. `await import('livekit-server-sdk')`. 

the [last comment](https://github.com/nestjs/nest/pull/8736#issuecomment-2011398600) in that thread points to an experimental node feature of `require(esm)`. 

I'll close this issue here.

**Comment by dvirarad** [comment]
I not sure I understand how can I solve this now with nestJS?

**Comment by thedewpoint** [comment]
For anyone coming here now who is stuck on this, this is the only thing I got working for me

```ts
import { Provider } from '@nestjs/common';

export const key = Symbol('LIVEKIT_CLIENT');
export type LivekitClientType = typeof import('livekit-server-sdk');
const dynamicImport = new Function('specifier', 'return import(specifier)');

export default {
  provide: key,
  useFactory: async () => {
    return await dynamicImport('livekit-server-sdk');
  },
} satisfies Provider;
```


usage:
```ts
import { Inject, Injectable, Logger } from '@nestjs/common';
import { key, type LivekitClientType } from './livekit.client';
import LivekitConfig from './livekit.config';
import { ConfigType } from '@nestjs/config';
import { type Room, RoomServiceClient } from 'livekit-server-sdk';

@Injectable()
export class LiveKitService {
  private roomServiceClient: RoomServiceClient;
  private logger = new Logger(LiveKitService.name);

  constructor(
    @Inject(key) livekit: LivekitClientType,
    @Inject(LivekitConfig.KEY) config: ConfigType<typeof LivekitConfig>,
  ) {
    const { livekitHost, livekitApiKey, livekitApiSecret } = config;
    if (!livekitHost || !livekitApiKey || !livekitApiSecret) {
      throw new Error(
        'LIVEKIT_API_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET are required',
      );
    }

    this.roomServiceClient = new livekit.RoomServiceClient(
      livekitHost,
      livekitApiKey,
      livekitApiSecret,
    );
  }
  public async createRoom(name: string): Promise<Room> {
    try {
      const res = await this.roomServiceClient.createRoom({
        name,
        emptyTimeout: 10 * 60,
      });
      return res;
    } catch (e) {
      this.logger.error(e);
      throw e;
    }
  }
}
```
