### ISSUE TITLE
mutePublishedTrack doesn't unmute tracks

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/server-sdk-js#15]
when you mute a track, it works fine:
`RoomServiceClient.mutePublishedTrack(room, identity, true) `

but it doesn't do anything if you try to unmute it:
`RoomServiceClient.mutePublishedTrack(room, identity, false) `

the TrackInfo returned by that last call incorrectly reports a muted=false, but if you query the participant trackinfo it will still report muted=true

tested on:
livekit-server-sdk 0.5.6
livekit-server 0.14.0

**Comment by davidzhao** [comment]
hey @alex-bluetrain, remote unmute is disabled by default due to privacy reasons. To enable it, you can set [enable_remote_unmute: true](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L79)

Let me know if that works.

**Comment by davidzhao** [comment]
though it's still an issue that it's reporting a success when it should've failed the request. we'll keep the issue open for that

**Comment by davidzhao** [comment]
this was fixed in https://github.com/livekit/livekit-server/commit/f9a1dd97c2677b7f08b805e1d3a65154c6d8f669
