### ISSUE TITLE
numParticipants is always 0 on every room returned by listRooms()

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/server-sdk-js#16]
When you run listRooms() and print the numParticipants of every room, it will always be 0
on the other hand, if you listParticipants() on every room, it will give you all the participants correctly.

tested on:
livekit-server-sdk 0.5.6
livekit-server 0.14.0

**Comment by lukasIO** [comment]
`numParticipants` is only present in the protocol and doesn't have any implementation yet.
