### ISSUE TITLE
I have some doubts and issues found.....

### ISSUE THREAD

**Issue by GRNHACKER** [livekit/server-sdk-js#23]
Issues:  
1. After successful connection between two user, i get the warning in server terminal that " channel congestion detected, updating channel capacity " and then connection gets poor.
2. When any user start screen sharing the quality suddenly started decreasing.

My doubts:
1. How can i set expiration of token using node js.
2. Can you please tell me the server requirement for 10,000 user at a time(both video audio).

**Comment by davidzhao** [comment]
closing dupe question to https://github.com/livekit/livekit-react/issues/32
