### ISSUE TITLE
[BUG] listEgress throws an error when trying to parse what is already JSON data

### ISSUE THREAD

**Issue by TheOptimisticFactory** [livekit/server-sdk-js#39]
### Summary

The method `egressClient.listEgress(roomName?)` is throwing `SyntaxError: Unexpected token o in JSON at position 1 ` because `JSON.parse` is invoked on a data structure that is already in a JSON format as seen on the following screenshot taken for a debugger attached to the nodeJS process:

![image](https://user-images.githubusercontent.com/2607260/173347855-b009258a-c229-4240-a8c3-5d642a86bdd6.png)

---

The error lies at the line of `EgressClient` in the function `listEgress`: https://github.com/livekit/server-sdk-js/blob/main/src/EgressClient.ts#L244

Using NodeJS v16.13.0 and livekit-server-sdk v1.0.0, `data` at line `238` is already in JSON format.
This causes the following error to be thrown: 

```javascript
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at EgressClient.<anonymous> (/api/node_modules/livekit-server-sdk/dist/EgressClient.js:184:31)
    at Generator.next (<anonymous>)
    at fulfilled (/api/node_modules/livekit-server-sdk/dist/EgressClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

---

### Issue Type

Bug Report

### Component Name

EgressClient

### OS / Environment

- Docker version 20.10.17, build 100c701
- NodeJS docker container v16.13.0
- livekit-server-sdk v1.0.0 (nodeJS dependency)
- Egress docker container v1.0
- Livekit docker container v1.0

### Steps to reproduce

Just run the following snippet. 

```javascript
  const egressClient = new EgressClient(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET);
  const egressListForRoom = await egressClient.listEgress(); // throws "SyntaxError: Unexpected token o in JSON at position 1"
```

**Comment by davidzhao** [comment]
@TheOptimisticFactory good point on the export. I'll make this change. ListEgress is fixed in #40

**Comment by davidzhao** [comment]
Type export complete in #41

**Comment by TheOptimisticFactory** [comment]
That was fast!
Thanks a lot.
