### ISSUE TITLE
livekit server example

### ISSUE THREAD

**Issue by MostafaALZOUBI1994** [livekit/server-sdk-js#44]
I made a lot of searches and I did not find any example or tutorial for js server, please provide it

**Comment by Nemra1** [comment]
+1

**Comment by davidzhao** [comment]
take a look at #48 for examples using webhooks. are you looking for examples for anything else?

**Comment by marcosdourado** [comment]
I think a good example would be managing a room, user and all.
As in the readme, but complete.
