### ISSUE TITLE
Send Data from server-sdk-js

### ISSUE THREAD

**Issue by litzbalane2017** [livekit/server-sdk-js#55]
Good Day.

I am trying to send custom message from the server side using the server-sdk-js. As an example code below:

```
app.get('/publish/:room', function(req, res, next) {
	if (allowedIp.indexOf(req.connection.remoteAddress) >-1)  {
		const encoder = new TextEncoder();
		const data = encoder.encode('hello world');
		const opts = {
			room: 'roomName',
			data: data,
			kind: DataPacket_Kind.RELIABLE,
		};
    svc.sendData(opts).then((_) => {
			res.json(_);
			console.log('Data published', _);
		}).catch((e) => {
	    console.log('Handle error here: ', e.message);
	    next();
	 	});
	} else {
		res.send("Publish fail");
	}
});
```

However, I am always getting error status 401. From what I can tell, do I need to pass token for the roomAdmin? 

Thank you.

**Comment by boks1971** [comment]
Yes, you would need a token with admin permissions to be able to do that. 401 is indicating invalid permissions.

**Comment by davidzhao** [comment]
`sendData` takes in the following parameters:

```
  async sendData(
    room: string,
    data: Uint8Array,
    kind: DataPacket_Kind,
    destinationSids: string[] = [],
  )
```

What is opts? You shouldn't need to pass in a token as the server SDK takes care of it automatically.

**Comment by lukasIO** [comment]
just to add to what @davidzhao already said, the arguments passed to `sendData` should *not* be a single object (like in your example), but rather spread out as individual arguments.
