### ISSUE TITLE
Bump jsonwebtoken to 9.0.0

### ISSUE THREAD

**Issue by fredrjoh** [livekit/server-sdk-js#57]
`jsonwebtoken` 8.5.1 has a security vulnerability: https://github.com/advisories/GHSA-27h2-hvpr-p74q. Please upgrade to 9.0.0.

**Comment by moham96** [comment]
I would actually suggest moving to another library like `jose` which works even on browsers

**Comment by davidzhao** [comment]
@fredrjoh thank you for the ping. this vulnerability does not impact us at the moment. nonetheless, we'll upgrade some of these dependencies shortly.

**Comment by hugoArregui** [comment]
I wanted to add one to this request since we are using this library and we are getting vulnerability reports because of the transient dependency of jsonwebtoken. Thanks!
