### ISSUE TITLE
Question about startEgress

### ISSUE THREAD

**Issue by nitedani** [livekit/server-sdk-js#58]
Is it guaranteed that `startTrackEgress` and `startTrackCompositeEgress`  will resolve only after an egress instance successfully started recording(status is started)?

My use case is the following:
1. I call and await startTrackCompositeEgress()
2. set {recording: true} on the room metadata
3. on client side(react) detect this change in metadata and update the UI

**Comment by davidzhao** [comment]
Yes, it should resolve only after it's successfully started. Both of those calls return an EgressInfo object.

To reflect that the room is being recorded, you'd listen to [RecordingStatusChanged](https://docs.livekit.io/client-sdk-js/enums/RoomEvent.html#RecordingStatusChanged) event, or check [Room.isRecording](https://docs.livekit.io/client-sdk-js/classes/Room.html#isRecording)
