### ISSUE TITLE
Using ingress breaks livekit.cloud project

### ISSUE THREAD

**Issue by smolgrrr** [livekit/server-sdk-js#78]
I'm trying to get the https://github.com/livekit-examples/livestream project to work locally, and came across a weird issue.

I can't get a stream started with the given Ingress presets, so I tried removing them to see if that would let me stream from OBS. Now, when I try create a RMTP URL I get a status 500 info (nothing useful in the response), and from that point forward any new API keys I generate are useless. To get new, working keys I need to create a new project on cloud.livekit.io

wait  - compiling /api/trpc/[trpc] (client and server)...
event - compiled successfully in 56 ms (131 modules)
❌ tRPC failed on ingress.create: Request failed with status code 500

      const ingress = await ingressClient.createIngress(
        IngressInput.RTMP_INPUT,
        {
          name: input.roomSlug,
          roomName: input.roomSlug,
          participantName: input.streamerName,
          participantIdentity: input.roomSlug,
          },
        }
      );

**Comment by davidzhao** [comment]
It's likely you've exceeded the max allowed Ingresses. Please check your project's quota for details.

If there are unused ingresses, ensure they are deleted before attempting to create a new one.

**Comment by smolgrrr** [comment]
Apologies for the fuss, not sure if anyone here has much experience with the livestream example project (https://github.com/livekit-examples/livestream/blob/main/src/server/api/routers/ingress.ts).

Streams work for me now, but I'm having trouble using Ingress controls per the documentation (https://docs.livekit.io/server/ingress/).
I was able to get a low quality stream working with audio by removing all video/audio specifications, but if I add a preset I don't seem to be able to get a working stream (and custom settings don't see to be settable in a javascript project). Is there a way I can just take the highest quality stream from simulcast instead of specifying when the ingress is created?
