### ISSUE TITLE
Subscribe/Unsubscribe to many users at the same time

### ISSUE THREAD

**Issue by DanielBerrioB** [livekit/server-sdk-js#80]
Hi, y'all!

I'm new in the LiveKit environment and I have a question. Is there a way I can update the subscriptions for many users instead of one by one? Because I ran into this:

I have a set of users (User 1, User 2, User 3, and User 4), so the idea is that User 1 can talk just to 2 of them or all of them, but I see that the only way to update the stream channel is by using the function `updateSubscriptions` individually.

```javascript
const changeUserSub = async (req, res) => {
    const { room } = req.params;
    const { users, sids, subscribe } = req.body;

    const usersPromises = users.map((user) => {
        return svc.updateSubscriptions(room, user, sids, subscribe);
    });

    try {
        await Promise.all(usersPromises);
    catch(_) {
        ...
    }
    ...
}
```

I have to loop in all the users and change the subscriptions one by one for doing something like this:

```json
    {
      "users": ["User 2", "User 3"],
      "sids": ["TR_AMfKU8MF3wGQjn"], // This is User 1 track id
      "subscribe": true
    }
```

Thanks!
Really appreciate it if someone can help me :)

**Comment by davidzhao** [comment]
I think the way you have it is the right way to approach it. There isn't a way to update it in bulk.

**Comment by DanielBerrioB** [comment]
@davidzhao another concern. Doing it this way is having a weird behavior, for some reason when updating some users (its subscriptions) are not being updated, and I end up just having a few of them with the right behavior, while the others keep subscribed or unsubscribed depending on the case. So basically it's not updating all the subscriptions.

Also, I found out that adding a little timer works (maybe the server needs some kind of wait until the subscription is done), but let's suppose I have 30 users, it'd take so long for this action to end. 

Any recommendations or suggestions you have?

Thanks for the help!!
