### ISSUE TITLE
Protobufjs import & ts compile error

### ISSUE THREAD

**Issue by zhangbanger** [livekit/server-sdk-js#9]
Ran into this issue via a Firebase Functions NodeJS project. I haven't had a chance to try outside of Firebase, but I think it shouldn't be Firebase specific, as it's the TS compiler that is tripping up over an import. I 
To repro (assuming you have a firebase account):

1. Get the firebase sdk `npm install -g firebase-tools`
2. Log into the account: `firebase login`
3. Create Functions: `firebase init functions` and choose Typescript. This essentially creates a Node Express project.
4. Modify the main.ts file with a livekit import `import {AccessToken} from "livekit-server-sdk";`
5. Run `npm install' in the functions dir
6. Add the "Create Access Tokens" [example](https://github.com/livekit/server-sdk-js#creating-access-tokens) into one of the functions (like "Hello" - doesn't matter which one, as long as the linter is happy).
7. Run `npm run build`, which should call the Typescript compiler.

The compiler should complain about the line from various `*.d.ts` files and the lack of a default export:

`import _m0 from "protobufjs/minimal";`

I fixed this by manually editing those files to look like:

`import * as _m0 from "protobufjs/minimal";`

I am on Node 14.17.6 and npm 6.14.15, but I have seen this issue in older and newer versions of both Node and npm.

**Comment by zhangandyx** [comment]
Here is a snippet from my main.ts

```
import * as functions from "firebase-functions";
import {AccessToken} from "livekit-server-sdk";

const API_KEY = "---------------";
const SECRET_KEY = "------------------------";

export const createRoom = functions.https.onCall(async (data) => {
  const roomName = data.room;
  const participantName = data.user;

  const at = new AccessToken(API_KEY, SECRET_KEY, {
    identity: participantName,
  });
  at.addGrant({
    roomCreate: true,
    roomJoin: true,
    room: roomName,
    canPublish: true,
    canSubscribe: true,
  });

  const token = at.toJwt();
  console.log("access token", token);
  return token;
});
```

**Comment by davidzhao** [comment]
Another user reported this, and they had a workaround:

```
I tried excluding node_modules from our tsconfig, but that didn't seem to help. Only when I added skipLibCheck: true did the build work.
This was with LiveKit Server SDK v0.5.6 and TS v4.1.3
```

**Comment by zhangbanger** [comment]
That makes total sense, and seems like the right thing to do in any case

**Comment by davidzhao** [comment]
reopening as others are also running into this. keeping it around to see if there's a better fix.

**Comment by davidzhao** [comment]
Another user reported seeing this with Node 14.

**Comment by harrisonlo** [comment]
I'm seeing this in Node 20 with `skipLibCheck` set to true. Any workaround?

**Comment by harrisonlo** [comment]
I'm seeing this in Node 20 without setting `skipLibCheck` to true.

**Comment by oyvindholmstad** [comment]
@davidzhao Seems like this bug was reintroduced with https://github.com/livekit/server-sdk-js/pull/24/commits/a7093842b3c8480ec2eeb4df9fc672455a8b43ee
