### ISSUE TITLE
Expose WebhookEvent type

### ISSUE THREAD

**Issue by utdemir** [livekit/server-sdk-js#90]
Hi! I have a small quality of live improvement request :).

When using this library from TypeScript, I was trying to write a function which takes a `WebhookEvent` (result of `WebhookReceiver.receive`), but I couldn't figure out how to get the type of `WebhookEvent` easily. 

Right now, here's how I am getting it, but as you can see that's a bit of a roundabout way of getting it:

```typescript
import * as livekit from 'livekit-server-sdk';
type LivekitWebhookEvent = ReturnType<
  InstanceType<typeof livekit.WebhookReceiver>['receive']
>;
```

I tried `import * as livekit from 'livekit-server-sdk/proto` but it didn't work for mysterious JavaScript module system reasons.

Nonetheless, I think it would be nice if it `WebhookEvent` was `export`ed from `index.ts` :).

**Comment by Ocupe** [comment]
Hello @utdemir, quality of live improvement are also very welcome.
For me importing the type like this worked:
```tsx
import { WebhookEvent } from 'livekit-server-sdk/dist/proto/livekit_webhook';
```
But I agree that it's not ideal, so I created a PR (#91 ) to change that. However, I'll let someone from the core maintainers decide if it makes sense to expose the type or not.
