### ISSUE TITLE
Cannot find module 'long'

### ISSUE THREAD

**Issue by moonrailgun** [livekit/server-sdk-js#96]
![image](https://github.com/livekit/server-sdk-js/assets/6964737/0344eb54-3e69-4c30-8a19-c9ef3ccbd462)

Its looks like you use long in `src/proto/livekit_ingress.ts` but not added into `dependencies` field in `package.json`

Did you visit it by shadow module? I cant use it in pnpm

**Comment by lukasIO** [comment]
`long` is a direct dependency through `protobufjs`. That should be sufficient. I'd be surprised if pnpm didn't handle this?

**Comment by moonrailgun** [comment]
The reason is that long is a dependency of protobufjs, and you directly reference long in your code.
The version of long will change with the upgrade of protobufjs, so this is not safe, and pnpm forcibly does not allow this behavior

**Comment by lukasIO** [comment]
closed via #99
